### ISSUE TITLE
Password is stored as plain text

### ISSUE THREAD

**Issue by SuperRembo** [wp-twinfield/wp-twinfield#25]
See https://github.com/wp-twinfield/wp-twinfield/blob/develop/classes/Settings.php#L156

**Comment by remcotolsma** [comment]
That is correct, we could store it encrypted, but if the code/function to encrypt/decrypt is available that doesn't add much security. The Twinfield "Web Services Authentication" (Session login) via username/password is also deprecated by Twinfield:

> Session login is deprecated and will be removed. End of life date will be announced later.
> For web services authentication use Open ID Connect instead

Source: https://accounting.twinfield.com/webservices/documentation/#/ApiReference/Authentication/WebServices

Use the "OpenID Connect Authentication" method instead.
